### ISSUE TITLE
PySimpleGUI.... is only the GUI....

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [pauldevos/mastering-python#1]
I like that you've got only PySimpleGUI listed under GUIs in your favorite libraries.  Yes, there is no other GUI that can compete with PySimpleGUI.    

I know of no other GUI library that enables you to run on both tkinter and Qt using the same source code.  Thanks for listing PySimpleGUI in your doc!

**Comment by pauldevos** [comment]
No problem! Thanks for creating such a great package!

**Comment by PySimpleGUI** [comment]
Wow I was, uhm, modest back in Dec 2018!  I've mellowed a bit since... a bit more modest & grateful perhaps.... or I hope....

![image](https://user-images.githubusercontent.com/46163555/168336842-8e8b2059-8364-4f3f-a09e-1c2bae98b634.png)

**Comment by PySimpleGUI** [comment]
I did at least write in the original docs, and it's still there now, that it's not THE best nor does it cover every situation a GUI is needed.  80% of the problem was the number I was shooting for covering.  There's room for multiple solutions.  I sponsor a couple of them in fact.  Every situation is unique.

**Comment by pauldevos** [comment]
Well, I appreciate the tip. I am more about content than delivery.

I am interested in doing a GUI project soonish. Cross-platform (e.g. iPhone, iPad, Mac, Windows). The Google Voice to Text API for an app to allow someone to transcribe the play-by-play of a basketball game to text. Which can later be parsed for stats. The main rub I think for GUI frameworks is trying to create something that can incorporate interfaces users are used to seeing in 2020+, e.g. Materials (Google) or Twitter-Bootstrap. Admittedly, I haven't looked into the codebases for the GUI frameworks enough to know how easy this is (already) or could be modified (perhaps OS contributions) -- although, admittedly, I'm more a Data Eng/Scientist in practice.

**Comment by PySimpleGUI** [comment]
> The main rub I think for GUI frameworks is trying to create something that can incorporate interfaces users are used to seeing in 2020

I've heard from folks on both sides of this one where appearance is the most important thing to them and with others, it's the functionality.

For a large portion of the PySimpleGUI users the thing they like the most is success,  I hear from a lot of people saying they could never have made what they made without PySimpleGUI.  This morning a user wrote:

> Thank you for creating this amazing GUI library! I couldn't have made this project without it

PySimpleGUI isn't the most attractive solution.  For some, that's going to knock it out of the running.   I'm OK with that.  I'll take the remainder of the pie  :-)

You definitely win the prize for the longest time between a comment on an issue.  Congratulations!  I love it!

**Comment by pauldevos** [comment]
lol -- hilarious -- I ALMOST commented that, I too have improved in 2022, e.g. my reply times =) 

Here's to getting better in 2022! 🤝

**Comment by PySimpleGUI** [comment]
![image](https://user-images.githubusercontent.com/46163555/168387764-f66e1961-1e83-4f6d-a9e5-c94eed3f48ff.png)
